[package]
name = "project2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version="3.0.10",features=["derive"]}
gtk4 = "0.4.6"
image = "0.23.0"
imageproc = "0.22.0"
